### ISSUE TITLE
repository server closed?

### ISSUE THREAD

**Issue by Hagazzusa** [deepmipt/hcn-dialogue-manager#1]
http://share.ipavlov.mipt.ru:8080/repository/datasets/dstc2.tar.gz

Trying to download a dataset dstc2.tar.gz from the repository
Connection error, retrying. (4 retries left)                
Connection error, retrying. (3 retries left)                
Connection error, retrying. (2 retries left)                
Connection error, retrying. (1 retries left)                
Connection error, retrying. (0 retries left)

**Comment by seliverstov** [comment]
Hi, currently repository server share.ipavlov.mipt.ru available only in private local network of the lab. When project will be ready we open repository server for all.
